### ISSUE TITLE
"./vendor/bin/phpunit: no such file or directory" when multiple project folders are opened

### ISSUE THREAD

**Issue by nikazooz** [itmecho/atom-phpunit#4]
When there are multiple project folders opened and the first one doesn't contain "vendor/bin/phpunit", we get error mentioned in the issue title.

One solution would be to set cwd to the path of project folder that contains file that we have opened and are running the commands from. This, however, means that we would have to run commands from that opened file and running 'run-suite' when there is no opened file would result in the same error.

I personaly find that approach more usable since I run tests from an opened file anyway. If you agree, I'll make a pull request.

**Comment by itmecho** [comment]
@nikazooz That sounds good to me! Maybe if there isn't an open file, we could loop over the projects and use the first one where `./vendor/bin/phpunit` exists? Then if none of the projects has `./vendor/bin/phpunit`, we can display an error notification telling the user that no projects contain `phpunit`.

**Comment by Gert-dev** [comment]
I wanted to chip in since there is a proper solution available that most package authors miss that I only know of because I've encountered the same issue: persist the path to the PHPUnit binary in project settings. With package settings, there is no way to properly cater towards users that have different setups across different projects: some projects might require a globally installed PHPUnit, others may have it in `vendor/bin`, still others might configure their own vendor path via Composer, some may not use Composer at all, etc.

You can achieve this by plugging into the service provided by the `atom-project-manager` plugin, which luckily also appears to be the most popular project manager package (it is unfortunate that Atom does not provide this functionality out of the box). You could still leave the setting in the package settings intact for users that do not wish to use such a project management package.

If you're looking for an example, I've done the same for the base package of [PHP Integrator](https://github.com/php-integrator/atom-base/tree/master/lib) (see Main.coffee as well as ProjectManager.coffee), which creates an looks for a `php` → `php_integrator` key in the project settings, you could do the same for `php` → `phpunit` or similar.

So far my attempt to get more packages to use project-specific settings rather than global settings :-).

**Comment by itmecho** [comment]
Thanks for the pull request @nikazooz! I'll review it ASAP! 

@Gert-dev That sounds like a good way of handling that. I'll have a play with it as soon as I can =]

**Comment by itmecho** [comment]
The original pull request is now in v1.3.0!

**Comment by nikazooz** [comment]
@Synapse791 Thanks for the work on the plugin, it's looking great! :)

**Comment by itmecho** [comment]
Excellent! Glad it's working for you
